   version: '3.8'

   services:
     mongo:
       image: mongo
       container_name: mongo
       ports:
         - "27017:27017"

     fastapi:
       build: ./fast
       container_name: fastapi
       ports:
         - "8000:8000"
       depends_on:
         - mongo

